version: '3'

services:
  pg_user_fi:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fi
      POSTGRES_PASSWORD: fi
      POSTGRES_DB: financial_institutions
    volumes:
      - db:/var/lib/postgresql/data
      